AnyoneForTennis/AnyoneForTennis/Controllers/CoachesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AnyoneForTennis.Data;
using AnyoneForTennis.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace AnyoneForTennis.Controllers
{
    public class CoachesController : Controller
    {
        private readonly AppDBContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public CoachesController(AppDBContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Coaches
        [Authorize(Roles = "Admin,Member")]
        public async Task<IActionResult> Index()
        {
            var Coaches = await _context.Coaches.ToListAsync();
            var retList = new List<CoachIndexViewModel>();

            foreach (var item in Coaches)
            {
                retList.Add(new CoachIndexViewModel {
                    CoachId = item.CoachId,
                    Name = item.Name
                });
            }

            if (this.User.IsInRole("Admin"))
            {
                ViewData["Role"] = "Admin";
            }
            else
            {
                ViewData["Role"] = "Member";
            }
            

            return View(retList);
        }

        // GET: Coaches/Details/5
        [Authorize(Roles = "Admin,Member")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coaches
                .FirstOrDefaultAsync(m => m.CoachId == id);
            if (coach == null)
            {
                return NotFound();
            }

            if (this.User.IsInRole("Admin"))
            {
                ViewData["Role"] = "Admin";
            }
            else
            {
                ViewData["Role"] = "Member";
            }

            return View(coach);
        }

        // GET: Coaches/Edit/5
        [Authorize(Roles = "Admin,Coach")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coaches.FindAsync(id);
            if (coach == null)
            {
                return NotFound();
            }

            var retCoach = new CoachEditViewModel {
                Name = coach.Name,
                CoachId = coach.CoachId,
                Age = coach.Age,
                Biography = coach.Biography
            };

            return View(retCoach);
        }

        // POST: Coaches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Coach")]
        public async Task<IActionResult> Edit(int id, [Bind("CoachId,Name,Age,Biography")] CoachEditViewModel coach)
        {
            if (id != coach.CoachId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var efCoach = _context.Coaches.Find(coach.CoachId);

                efCoach.Biography = coach.Biography;
                efCoach.Age = coach.Age;
                efCoach.Name = coach.Name;

                _context.Update(efCoach);
                await _context.SaveChangesAsync();

                if (this.User.IsInRole("Admin"))
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(coach);
        }

        // GET: Coaches/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var coach = await _context.Coaches
                .FirstOrDefaultAsync(m => m.CoachId == id);
            if (coach == null)
            {
                return NotFound();
            }

            return View(coach);
        }

        // POST: Coaches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coach = await _context.Coaches.FindAsync(id);
            _context.Coaches.Remove(coach);

            var coachLogin = await _userManager.FindByNameAsync(coach.Username);
            await _userManager.DeleteAsync(coachLogin);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CoachExists(int id)
        {
            return _context.Coaches.Any(e => e.CoachId == id);
        }
    }
}

AnyoneForTennis/AnyoneForTennis/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AnyoneForTennis.Data;
using AnyoneForTennis.Models;
using Microsoft.AspNetCore.Authorization;

namespace AnyoneForTennis.Controllers
{
    public class EventsController : Controller
    {
        private readonly AppDBContext _context;

        public EventsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Events
        [Authorize]
        public async Task<IActionResult> Index()
        {
            if (this.User.IsInRole("Member"))
            {
                var Events = await _context.Events.ToListAsync();
                var Coaches = await _context.Coaches.ToListAsync();
                var EventMembers = await _context.EventMembers.ToListAsync();

                var retList = new List<Event>();
                var user = new Member();

                foreach (var item in _context.Members)
                {
                    if (item.Username.CompareTo(this.User.Identity.Name) == 0)
                    {
                        user = item;
                        break;
                    }
                }

                foreach (var item in Events)
                {
                    var temp = new EventMember {
                        EventId = item.EventId,
                        Event = item,
                        MemberId = user.MemberId,
                        Member = user
                    };
                    if (item.EventMembers != null)
                    {
                        foreach (var @event in item.EventMembers)
                        {
                            if (@event.EventId == item.EventId && @event.MemberId == user.MemberId)
                            {
                                retList.Add(item);
                            }
                        }
                    }
                }

                ViewData["Role"] = "Member";
                return View(retList);
            }
            //-------------------------------------------------------------------------------
            else if (this.User.IsInRole("Coach"))
            {
                var Events = await _context.Events.ToListAsync();
                var coaches = await _context.Coaches.ToListAsync();
                var retList = new List<Event>();
                var user = new Coach();

                foreach (var item in _context.Coaches)
                {
                    if (item.Username.CompareTo(this.User.Identity.Name) == 0)
                    {
                        user = item;
                        break;
                    }
                }

                foreach (var item in Events)
                {
                    if (item.RunningCoach.CoachId == user.CoachId)
                    {
                        retList.Add(item);
                    }
                }

                ViewData["Role"] = "Coach";
                return View(retList);
            }
            //----------------------------------------------------------------------------
            else
            {
                ViewData["Role"] = "Admin";
                return View(await _context.Events.ToListAsync());
            }
        }

        // GET: Events/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            var members = new List<string>();

            @event.EventMembers = new List<EventMember>();

            foreach (var item in _context.EventMembers)
            {
                if (item.EventId == @event.EventId)
                {
                    members.Add(_context.Members.Find(item.MemberId).Username);
                }
            }

            if (@event.EventMembers.Count == 0)
            {
                members.Add("No one is enrolled in this event yet.");
            }

            var retEvent = new EventDetailsViewModel
            {
                Id = (int)id,
                Date = @event.Date,
                Location = @event.Location,
                Name = @event.Name,
                RunningCoach = _context.Coaches.Find(@event.CoachId).Name,
                CoachId = @event.CoachId,
                Members = members
            };

            if (this.User.IsInRole("Coach"))
            {
                ViewData["Role"] = "Coach";
            }
            else if (this.User.IsInRole("Admin"))
            {
                ViewData["Role"] = "Admin";
            }
            else
            {
                ViewData["Role"] = "Member";
            }
            return View(retEvent);
        }

        // GET: Events/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CoachId"] = new SelectList(_context.Coaches, "CoachId", "Name");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("EventId,Name,Date,Location")] Event @event, int RunningCoach)
        {
            if (ModelState.IsValid)
            {
                @event.RunningCoach = _context.Coaches.Find(RunningCoach);
                @event.CoachId = RunningCoach;

                _context.Add(@event);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["CoachId"] = new SelectList(_context.Coaches, "CoachId", "Name", @event.RunningCoach.CoachId);
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }

            var retEvent = new EventEditViewModel
            {
                EventId = @event.EventId,
                Date = @event.Date,
                Location = @event.Location,
                Name = @event.Name,
                RunningCoach = _context.Coaches.Find(@event.CoachId)
            };

            //Todo figure out why this keeps selecting the wrong value on page load
            ViewData["CoachId"] = new SelectList(_context.Coaches, "CoachId", "Name", @event.CoachId);
            return View(retEvent);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,Name,Date,Location")] EventEditViewModel @event, int RunningCoach)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var efEvent = _context.Events.Find(@event.EventId);

                efEvent.RunningCoach = _context.Coaches.Find(RunningCoach);
                efEvent.CoachId = RunningCoach;

                _context.Update(efEvent);
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }

            ViewData["CoachId"] = new SelectList(_context.Coaches, "CoachId", "Name", @event.RunningCoach.CoachId);
            return View(@event);
        }

        // GET: Events/Enroll/5
        [Authorize(Roles = "Member,Admin")]
        public async Task<IActionResult> Enroll(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }

            var retEvent = new EventEnrollViewModel
            {
                Id = (int)id,
                Date = @event.Date,
                Location = @event.Location,
                Name = @event.Name,
                RunningCoach = _context.Coaches.Find(@event.CoachId).Name
            };

            return View(retEvent);
        }

        // POST: Events/Enroll/5
        [HttpPost, ActionName("Enroll")]
        [Authorize(Roles = "Member,Admin")]
        public async Task<IActionResult> EnrollConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var efEvent = await _context.Events.FindAsync(id);
            if (efEvent == null)
            {
                return NotFound();
            }

            var user = new Member();

            foreach (var item in _context.Members)
            {
                if (this.User.Identity.Name.CompareTo(item.Username) == 0)
                {
                    user = item;
                    break;
                }
            }

            if (efEvent.EventMembers != null)
            {
                efEvent.EventMembers.Add(new EventMember {
                EventId = efEvent.EventId,
                MemberId = user.MemberId

AnyoneForTennis/AnyoneForTennis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnyoneForTennis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AnyoneForTennis</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            var value = new Byte[20];
                            bool succ = Context.Session.TryGetValue("Role", out value);

                            if (succ)
                            {
                                var role = System.Text.Encoding.UTF8.GetString(value);

                                if (role.CompareTo("Admin") == 0)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">My Schedule</a>
                                    </li>
                                }

                                if (role.CompareTo("Admin") == 0)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Coaches" asp-action="Index">Coaches</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                                    </li>
                                }
                                else if (role.CompareTo("Coach") == 0)
                                {
                                    value = null;
                                    succ = Context.Session.TryGetValue("Id", out value);

                                    if (succ)
                                    {
                                        int intValue;
                                        var notInt = System.Text.Encoding.UTF8.GetString(value);
                                        var intSucc = Int32.TryParse(notInt, out intValue);

                                        if (intSucc)
                                        {
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Coaches" asp-action="Edit" asp-route-id="@intValue">Edit Profile</a>
                                            </li>
                                        }
                                    }
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="EventList">Browse Events</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Coaches" asp-action="Index">Coaches</a>
                                    </li>
                                }
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AnyoneForTennis
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

AnyoneForTennis/AnyoneForTennis/Views/Shared/_Layout_NoHeader.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnyoneForTennis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AnyoneForTennis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>